In [2]:
!pip install pandas pyarrow fastparquet

Requirement already satisfied: pandas in b:\gitprojects\github\examitmo\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: pyarrow in b:\gitprojects\github\examitmo\.venv\lib\site-packages (21.0.0)
Requirement already satisfied: fastparquet in b:\gitprojects\github\examitmo\.venv\lib\site-packages (2024.11.0)
Requirement already satisfied: numpy>=1.26.0 in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: cramjam>=2.3 in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from fastparquet) (2.10.0)
Requirement already satisfied: fsspec in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from fastparquet) (2025.7.0)
Requirement already satisfied: packaging in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from fastparquet) (25.0)
Requirement already satisfied: six>=1.5 in b:\gitprojects\github\examitmo\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [4]:
df_exchange = pd.read_parquet('historical_currency_exchange.parquet')

df_transactions = pd.read_parquet('transaction_fraud_data.parquet')
# Разбиваем словарь last_hour_activity на отдельные столбцы
df_transactions = pd.concat([
    df_transactions.drop('last_hour_activity', axis=1),
    pd.json_normalize(df_transactions['last_hour_activity'])
], axis=1)
df_transactions

,transaction_id,customer_id,card_number,timestamp,vendor_category,vendor_type,vendor,amount,currency,country,city,city_size,card_type,is_card_present,device,channel,device_fingerprint,ip_address,is_outside_home_country,is_high_risk_vendor,is_weekend,is_fraud,num_transactions,total_amount,unique_merchants,unique_countries,max_single_amount
0,TX_a0ad2a2a,CUST_72886,6646734767813109,2024-09-30 00:00:01.034820,Restaurant,fast_food,Taco Bell,294.87,GBP,UK,Unknown City,medium,Platinum Credit,False,iOS App,mobile,e8e6160445c935fd0001501e4cbac8bc,197.153.60.199,False,False,False,False,1197,3.349856e+07,105,12,1.925481e+06
1,TX_3599c101,CUST_70474,376800864692727,2024-09-30 00:00:01.764464,Entertainment,gaming,Steam,3368.97,BRL,Brazil,Unknown City,medium,Platinum Credit,False,Edge,web,a73043a57091e775af37f252b3a32af9,208.123.221.203,True,True,False,True,509,2.011476e+07,100,12,5.149117e+06
2,TX_a9461c6d,CUST_10715,5251909460951913,2024-09-30 00:00:02.273762,Grocery,physical,Whole Foods,102582.38,JPY,Japan,Unknown City,medium,Platinum Credit,False,Firefox,web,218864e94ceaa41577d216b149722261,10.194.159.204,False,False,False,False,332,3.916385e+07,97,12,1.852242e+06
3,TX_7be21fc4,CUST_16193,376079286931183,2024-09-30 00:00:02.297466,Gas,major,Exxon,630.60,AUD,Australia,Unknown City,medium,Premium Debit,False,iOS App,mobile,70423fa3a1e74d01203cf93b51b9631d,17.230.177.225,False,False,False,False,764,2.201260e+07,105,12,2.055798e+06
4,TX_150f490b,CUST_87572,6172948052178810,2024-09-30 00:00:02.544063,Healthcare,medical,Medical Center,724949.27,NGN,Nigeria,Unknown City,medium,Basic Debit,False,Chrome,web,9880776c7b6038f2af86bd4e18a1b1a4,136.241.219.151,True,False,False,True,218,4.827636e+06,88,12,1.157231e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7483761,TX_58a762fa,CUST_11344,377055034743699,2024-10-30 23:59:58.926575,Retail,online,AliExpress,887.32,SGD,Singapore,Unknown City,medium,Premium Debit,False,Safari,web,2e37bb086e754bfaf2ec3806dcac8d98,248.8.111.152,False,False,False,False,1,1.521769e+03,1,1,8.873226e+02
7483762,TX_dabcf671,CUST_38961,373625915641065,2024-10-30 23:59:58.950801,Grocery,physical,Kroger,356.06,EUR,France,Unknown City,medium,Platinum Credit,False,Chrome,web,459c67dbfbb15019df8088fc0f2ffe1d,224.123.137.90,False,False,False,False,0,3.560645e+02,0,0,3.560645e+02
7483763,TX_ab567eb4,CUST_75576,6702342842796660,2024-10-30 23:59:58.972155,Grocery,physical,Kroger,391.96,SGD,Singapore,Unknown City,medium,Premium Debit,False,Safari,web,337d36a8f5e811564a1dd3c255db01dd,31.196.9.234,False,False,False,False,0,3.919607e+02,0,0,3.919607e+02
7483764,TX_5ae61846,CUST_82508,374615717295581,2024-10-30 23:59:58.996608,Retail,online,eBay,601.71,USD,USA,Chicago,large,Basic Credit,False,Firefox,web,52874c17f4ab0846fac1aed0c66e8551,188.74.107.8,False,False,False,False,2,1.474510e+03,2,1,6.017100e+02
7483765,TX_54fccca9,CUST_20139,373017396639208,2024-10-30 23:59:59.101885,Grocery,online,Walmart Grocery,40668.06,JPY,Japan,Unknown City,medium,Gold Credit,False,Chrome,web,e9e0e0db1c95f5f44613492b2f931fac,205.233.99.48,False,False,False,False,0,4.066806e+04,0,0,4.066806e+04

In [5]:
df_exchange.head()

,date,AUD,BRL,CAD,EUR,GBP,JPY,MXN,NGN,RUB,SGD,USD
0,2024-09-30,1.443654,5.434649,1.351196,0.895591,0.747153,142.573268,19.694724,1668.736400,94.133735,1.280156,1
1,2024-10-01,1.442917,5.444170,1.352168,0.897557,0.746956,143.831429,19.667561,1670.694524,92.898519,1.284352,1
2,2024-10-02,1.449505,5.425444,1.348063,0.903056,0.752241,143.806861,19.606748,1669.653006,94.583198,1.286983,1
3,2024-10-03,1.456279,5.442044,1.351451,0.906018,0.754584,146.916773,19.457701,1670.097873,95.655442,1.294391,1
4,2024-10-04,1.460930,5.477788,1.355260,0.906452,0.761891,146.592323,19.363467,1649.763738,94.755337,1.296800,1

In [6]:
df_transactions[['timestamp', 'amount', 'currency', 'total_amount', 'max_single_amount']].head()

,timestamp,amount,currency,total_amount,max_single_amount
0,2024-09-30 00:00:01.034820,294.87,GBP,3.349856e+07,1.925481e+06
1,2024-09-30 00:00:01.764464,3368.97,BRL,2.011476e+07,5.149117e+06
2,2024-09-30 00:00:02.273762,102582.38,JPY,3.916385e+07,1.852242e+06
3,2024-09-30 00:00:02.297466,630.60,AUD,2.201260e+07,2.055798e+06
4,2024-09-30 00:00:02.544063,724949.27,NGN,4.827636e+06,1.157231e+06

In [7]:
def standardize_to_usd(
    df_transactions: pd.DataFrame,
    df_exchange: pd.DataFrame
) -> pd.DataFrame:
    """
    Добавляет в df_transactions колонки с эквивалентом в USD:
    - amount_usd,
    - total_amount_usd,
    - max_single_amount_usd.

    Параметры
    ----------
    df_transactions : pd.DataFrame
        Строки транзакций с полями:
        ['date', 'amount', 'currency', 'total_amount', 'max_single_amount'].
    df_exchange : pd.DataFrame
        Курсы валют по датам:
        столбец 'date' + колонки по коду валют (значение — единиц валюты за 1 USD).

    Возвращает
    -------
    pd.DataFrame
        Исходный df_transactions с доп. колонками:
        ['amount_usd', 'total_amount_usd', 'max_single_amount_usd'].
    """
    # Копируем и приводим даты
    df_transactions['date'] = pd.to_datetime(df_transactions['timestamp'].dt.date)
    df_exchange['date'] = pd.to_datetime(df_exchange['date'])

    # Переводим df_exchange в «длинный» формат: date | currency | rate
    exchange_long = (
        df_exchange
        .melt(id_vars=['date'], var_name='currency', value_name='rate')
    )

    # Объединяем по date + currency
    df_merged = df_transactions.merge(exchange_long, on=['date', 'currency'], how='left')

    # Конвертация: rate — единиц валюты за 1 USD
    df_merged['amount'] = df_merged['amount'] / df_merged['rate']
    df_merged['total_amount'] = df_merged['total_amount'] / df_merged['rate']
    df_merged['max_single_amount'] = df_merged['max_single_amount'] / df_merged['rate']
    df_merged = df_merged.drop(columns=['date', 'rate', 'currency'])
    df_merged.to_parquet('transactions_usd.parquet')
    return df_merged

standardize_to_usd(df_transactions, df_exchange)

,transaction_id,customer_id,card_number,timestamp,vendor_category,vendor_type,vendor,amount,country,city,city_size,card_type,is_card_present,device,channel,device_fingerprint,ip_address,is_outside_home_country,is_high_risk_vendor,is_weekend,is_fraud,num_transactions,total_amount,unique_merchants,unique_countries,max_single_amount
0,TX_a0ad2a2a,CUST_72886,6646734767813109,2024-09-30 00:00:01.034820,Restaurant,fast_food,Taco Bell,394.658011,UK,Unknown City,medium,Platinum Credit,False,iOS App,mobile,e8e6160445c935fd0001501e4cbac8bc,197.153.60.199,False,False,False,False,1197,4.483492e+07,105,12,2.577089e+06
1,TX_3599c101,CUST_70474,376800864692727,2024-09-30 00:00:01.764464,Entertainment,gaming,Steam,619.905757,Brazil,Unknown City,medium,Platinum Credit,False,Edge,web,a73043a57091e775af37f252b3a32af9,208.123.221.203,True,True,False,True,509,3.701207e+06,100,12,9.474609e+05
2,TX_a9461c6d,CUST_10715,5251909460951913,2024-09-30 00:00:02.273762,Grocery,physical,Whole Foods,719.506409,Japan,Unknown City,medium,Platinum Credit,False,Firefox,web,218864e94ceaa41577d216b149722261,10.194.159.204,False,False,False,False,332,2.746928e+05,97,12,1.299151e+04
3,TX_7be21fc4,CUST_16193,376079286931183,2024-09-30 00:00:02.297466,Gas,major,Exxon,436.808287,Australia,Unknown City,medium,Premium Debit,False,iOS App,mobile,70423fa3a1e74d01203cf93b51b9631d,17.230.177.225,False,False,False,False,764,1.524784e+07,105,12,1.424024e+06
4,TX_150f490b,CUST_87572,6172948052178810,2024-09-30 00:00:02.544063,Healthcare,medical,Medical Center,434.430069,Nigeria,Unknown City,medium,Basic Debit,False,Chrome,web,9880776c7b6038f2af86bd4e18a1b1a4,136.241.219.151,True,False,False,True,218,2.892989e+03,88,12,6.934776e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7483761,TX_58a762fa,CUST_11344,377055034743699,2024-10-30 23:59:58.926575,Retail,online,AliExpress,670.362079,Singapore,Unknown City,medium,Premium Debit,False,Safari,web,2e37bb086e754bfaf2ec3806dcac8d98,248.8.111.152,False,False,False,False,1,1.149682e+03,1,1,6.703641e+02
7483762,TX_dabcf671,CUST_38961,373625915641065,2024-10-30 23:59:58.950801,Grocery,physical,Kroger,385.402905,France,Unknown City,medium,Platinum Credit,False,Chrome,web,459c67dbfbb15019df8088fc0f2ffe1d,224.123.137.90,False,False,False,False,0,3.854078e+02,0,0,3.854078e+02
7483763,TX_ab567eb4,CUST_75576,6702342842796660,2024-10-30 23:59:58.972155,Grocery,physical,Kroger,296.122166,Singapore,Unknown City,medium,Premium Debit,False,Safari,web,337d36a8f5e811564a1dd3c255db01dd,31.196.9.234,False,False,False,False,0,2.961227e+02,0,0,2.961227e+02
7483764,TX_5ae61846,CUST_82508,374615717295581,2024-10-30 23:59:58.996608,Retail,online,eBay,601.710000,USA,Chicago,large,Basic Credit,False,Firefox,web,52874c17f4ab0846fac1aed0c66e8551,188.74.107.8,False,False,False,False,2,1.474510e+03,2,1,6.017100e+02
7483765,TX_54fccca9,CUST_20139,373017396639208,2024-10-30 23:59:59.101885,Grocery,online,Walmart Grocery,265.526634,Japan,Unknown City,medium,Gold Credit,False,Chrome,web,e9e0e0db1c95f5f44613492b2f931fac,205.233.99.48,False,False,False,False,0,2.655266e+02,0,0,2.655266e+02

### Мы стандартизировали валюты в USD, теперь нам не нужно хранить таблицу с курсами валют, чтоб снижает нагрузка на память.

## Теперь мы оптимизируем поля String и Int64

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
df_transactions = pd.read_parquet('transactions_usd.parquet')

# Сразу выведем много информации, чтоб сюда постоянно поглядывать
print('Посмотрим на первые строки:')
display(df_transactions.head())

print('Посмотрим на информацию о данных:')
display(df_transactions.info())

print('Посмотрим на описательные статистики:')
display(df_transactions.describe())

print('Посмотрим на количество nulls:')
display(df_transactions.isnull().sum())

print('Посмотрим на количество дубликатов:')
display(df_transactions.duplicated().sum())

print('Посмотрим на количество уникальных значений:')
display(df_transactions.nunique())

print('Посмотрим на количество строк и столбцов:')
display(df_transactions.shape)

print('Посмотрим на названия столбцов:')
display(df_transactions.columns)

Посмотрим на первые строки:

,transaction_id,customer_id,card_number,timestamp,vendor_category,vendor_type,vendor,amount,country,city,city_size,card_type,is_card_present,device,channel,device_fingerprint,ip_address,is_outside_home_country,is_high_risk_vendor,is_weekend,is_fraud,num_transactions,total_amount,unique_merchants,unique_countries,max_single_amount
0,TX_a0ad2a2a,CUST_72886,6646734767813109,2024-09-30 00:00:01.034820,Restaurant,fast_food,Taco Bell,394.658011,UK,Unknown City,medium,Platinum Credit,False,iOS App,mobile,e8e6160445c935fd0001501e4cbac8bc,197.153.60.199,False,False,False,False,1197,4.483492e+07,105,12,2.577089e+06
1,TX_3599c101,CUST_70474,376800864692727,2024-09-30 00:00:01.764464,Entertainment,gaming,Steam,619.905757,Brazil,Unknown City,medium,Platinum Credit,False,Edge,web,a73043a57091e775af37f252b3a32af9,208.123.221.203,True,True,False,True,509,3.701207e+06,100,12,9.474609e+05
2,TX_a9461c6d,CUST_10715,5251909460951913,2024-09-30 00:00:02.273762,Grocery,physical,Whole Foods,719.506409,Japan,Unknown City,medium,Platinum Credit,False,Firefox,web,218864e94ceaa41577d216b149722261,10.194.159.204,False,False,False,False,332,2.746928e+05,97,12,1.299151e+04
3,TX_7be21fc4,CUST_16193,376079286931183,2024-09-30 00:00:02.297466,Gas,major,Exxon,436.808287,Australia,Unknown City,medium,Premium Debit,False,iOS App,mobile,70423fa3a1e74d01203cf93b51b9631d,17.230.177.225,False,False,False,False,764,1.524784e+07,105,12,1.424024e+06
4,TX_150f490b,CUST_87572,6172948052178810,2024-09-30 00:00:02.544063,Healthcare,medical,Medical Center,434.430069,Nigeria,Unknown City,medium,Basic Debit,False,Chrome,web,9880776c7b6038f2af86bd4e18a1b1a4,136.241.219.151,True,False,False,True,218,2.892989e+03,88,12,6.934776e+02

Посмотрим на информацию о данных:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7483766 entries, 0 to 7483765
Data columns (total 26 columns):
 #   Column                   Dtype
---  ------                   -----
 0   transaction_id           object
 1   customer_id              object
 2   card_number              int64
 3   timestamp                datetime64[us]
 4   vendor_category          object
 5   vendor_type              object
 6   vendor                   object
 7   amount                   float64
 8   country                  object
 9   city                     object
 10  city_size                object
 11  card_type                object
 12  is_card_present          bool
 13  device                   object
 14  channel                  object
 15  device_fingerprint       object
 16  ip_address               object
 17  is_outside_home_country  bool
 18  is_high_risk_vendor      bool
 19  is_weekend               bool
 20  is_fraud                 bool
 21  num_transactions         int64
 22  total_amount             float64
 23  unique_merchants         int64
 24  unique_countries         int64
 25  max_single_amount        float64
dtypes: bool(5), datetime64[us](1), float64(3), int64(4), object(13)
memory usage: 1.2+ GB

None

Посмотрим на описательные статистики:

,card_number,timestamp,amount,num_transactions,total_amount,unique_merchants,unique_countries,max_single_amount
count,7.483766e+06,7483766,7.483766e+06,7.483766e+06,7.483766e+06,7.483766e+06,7.483766e+06,7.483766e+06
mean,4.222100e+15,2024-10-15 12:36:38.052469,5.426347e+02,4.091429e+02,7.118837e+06,8.002226e+01,1.066260e+01,8.567670e+05
min,3.700086e+14,2024-09-30 00:00:01.034820,2.406185e-03,0.000000e+00,6.708314e-03,0.000000e+00,0.000000e+00,5.045205e-03
25%,4.004400e+15,2024-10-07 18:08:27.325326,1.686272e+02,1.050000e+02,1.115306e+05,6.300000e+01,1.100000e+01,1.353022e+04
50%,5.010745e+15,2024-10-15 12:46:31.739295,3.592600e+02,2.920000e+02,1.268625e+06,9.500000e+01,1.200000e+01,2.490535e+05
75%,5.999914e+15,2024-10-23 07:37:00.969509,6.155200e+02,6.060000e+02,7.968878e+06,1.040000e+02,1.200000e+01,1.156496e+06
max,6.999728e+15,2024-10-30 23:59:59.101885,1.578154e+04,3.962000e+03,1.378987e+09,1.050000e+02,1.200000e+01,8.330037e+06
std,2.341170e+15,NaN,7.284294e+02,3.910964e+02,1.749774e+07,3.047287e+01,2.617777e+00,1.273214e+06

Посмотрим на количество nulls:

transaction_id             0
customer_id                0
card_number                0
timestamp                  0
vendor_category            0
vendor_type                0
vendor                     0
amount                     0
country                    0
city                       0
city_size                  0
card_type                  0
is_card_present            0
device                     0
channel                    0
device_fingerprint         0
ip_address                 0
is_outside_home_country    0
is_high_risk_vendor        0
is_weekend                 0
is_fraud                   0
num_transactions           0
total_amount               0
unique_merchants           0
unique_countries           0
max_single_amount          0
dtype: int64

Посмотрим на количество дубликатов:

np.int64(0)

Посмотрим на количество уникальных значений:

transaction_id             7477306
customer_id                   4869
card_number                   5000
timestamp                  7483754
vendor_category                  8
vendor_type                     17
vendor                         105
amount                     6684564
country                         12
city                            11
city_size                        2
card_type                        5
is_card_present                  2
device                           9
channel                          3
device_fingerprint          785462
ip_address                 7477187
is_outside_home_country          2
is_high_risk_vendor              2
is_weekend                       2
is_fraud                         2
num_transactions              3538
total_amount               7483717
unique_merchants               106
unique_countries                13
max_single_amount          2172590
dtype: int64

Посмотрим на количество строк и столбцов:

(7483766, 26)

Посмотрим на названия столбцов:

Index(['transaction_id', 'customer_id', 'card_number', 'timestamp',
       'vendor_category', 'vendor_type', 'vendor', 'amount', 'country', 'city',
       'city_size', 'card_type', 'is_card_present', 'device', 'channel',
       'device_fingerprint', 'ip_address', 'is_outside_home_country',
       'is_high_risk_vendor', 'is_weekend', 'is_fraud', 'num_transactions',
       'total_amount', 'unique_merchants', 'unique_countries',
       'max_single_amount'],
      dtype='object')

In [4]:
# Анализ типов данных для оптимизации памяти
print("=== АНАЛИЗ ТИПОВ ДАННЫХ ДЛЯ ОПТИМИЗАЦИИ ===")
print(f"Общий размер в памяти: {df_transactions.memory_usage(deep=True).sum() / 1024**3:.2f} GB")
print()

# Анализируем каждый столбец
for col in df_transactions.columns:
    dtype = df_transactions[col].dtype
    memory_mb = df_transactions[col].memory_usage(deep=True) / 1024**2
    
    print(f"{col:25} | {str(dtype):15} | {memory_mb:6.1f} MB", end="")
    
    if dtype == 'object':
        unique_count = df_transactions[col].nunique()
        total_count = len(df_transactions)
        ratio = unique_count / total_count
        print(f" | Уникальных: {unique_count:7} ({ratio:.4f})")
    elif dtype in ['int64', 'Int64']:
        min_val = df_transactions[col].min()
        max_val = df_transactions[col].max()
        print(f" | Диапазон: {min_val} - {max_val}")
    else:
        print()

print("\n=== АНАЛИЗ STRING СТОЛБЦОВ ===")
string_columns = df_transactions.select_dtypes(include=['object']).columns
for col in string_columns:
    unique_vals = df_transactions[col].nunique()
    total_vals = len(df_transactions)
    ratio = unique_vals / total_vals
    print(f"{col:25} | Уникальных: {unique_vals:7} | Соотношение: {ratio:.6f}")
    if unique_vals <= 20:  # Покажем все уникальные значения для малых множеств
        print(f"                          Значения: {sorted(df_transactions[col].unique())}")
    print()

=== АНАЛИЗ ТИПОВ ДАННЫХ ДЛЯ ОПТИМИЗАЦИИ ===
Общий размер в памяти: 5.88 GB

transaction_id            | object          |  428.2 MB | Уникальных: 7477306 (0.9991)
customer_id               | object          |  421.1 MB | Уникальных:    4869 (0.0007)
card_number               | int64           |   57.1 MB | Диапазон: 370008611452264 - 6999728403598762
timestamp                 | datetime64[us]  |   57.1 MB
vendor_category           | object          |  406.8 MB | Уникальных:       8 (0.0000)
vendor_type               | object          |  399.1 MB | Уникальных:      17 (0.0000)
vendor                    | object          |  416.5 MB | Уникальных:     105 (0.0000)
amount                    | float64         |   57.1 MB
country                   | object          |  393.0 MB | Уникальных:      12 (0.0000)
city                      | object          |  433.7 MB | Уникальных:      11 (0.0000)
city_size                 | object          |  392.3 MB | Уникальных:       2 (0.0000)
card_type                 | object          |  438.4 MB | Уникальных:       5 (0.0000)
is_card_present           | bool            |    7.1 MB
device                    | object          |  401.7 MB | Уникальных:       9 (0.0000)
channel                   | object          |  377.6 MB | Уникальных:       3 (0.0000)
device_fingerprint        | object          |  578.1 MB | Уникальных:  785462 (0.1050)
ip_address                | object          |  444.6 MB | Уникальных: 7477187 (0.9991)
is_outside_home_country   | bool            |    7.1 MB
is_high_risk_vendor       | bool            |    7.1 MB
is_weekend                | bool            |    7.1 MB
is_fraud                  | bool            |    7.1 MB
num_transactions          | int64           |   57.1 MB | Диапазон: 0 - 3962
total_amount              | float64         |   57.1 MB
unique_merchants          | int64           |   57.1 MB | Диапазон: 0 - 105
unique_countries          | int64           |   57.1 MB | Диапазон: 0 - 12
max_single_amount         | float64         |   57.1 MB

=== АНАЛИЗ STRING СТОЛБЦОВ ===
transaction_id            | Уникальных: 7477306 | Соотношение: 0.999137

customer_id               | Уникальных:    4869 | Соотношение: 0.000651

vendor_category           | Уникальных:       8 | Соотношение: 0.000001
                          Значения: ['Education', 'Entertainment', 'Gas', 'Grocery', 'Healthcare', 'Restaurant', 'Retail', 'Travel']

vendor_type               | Уникальных:      17 | Соотношение: 0.000002
                          Значения: ['airlines', 'booking', 'casual', 'events', 'fast_food', 'gaming', 'hotels', 'local', 'major', 'medical', 'online', 'pharmacy', 'physical', 'premium', 'streaming', 'supplies', 'transport']

vendor                    | Уникальных:     105 | Соотношение: 0.000014

country                   | Уникальных:      12 | Соотношение: 0.000002
                          Значения: ['Australia', 'Brazil', 'Canada', 'France', 'Germany', 'Japan', 'Mexico', 'Nigeria', 'Russia', 'Singapore', 'UK', 'USA']

city                      | Уникальных:      11 | Соотношение: 0.000001
                          Значения: ['Chicago', 'Dallas', 'Houston', 'Los Angeles', 'New York', 'Philadelphia', 'Phoenix', 'San Antonio', 'San Diego', 'San Jose', 'Unknown City']

city_size                 | Уникальных:       2 | Соотношение: 0.000000
                          Значения: ['large', 'medium']

card_type                 | Уникальных:       5 | Соотношение: 0.000001
                          Значения: ['Basic Credit', 'Basic Debit', 'Gold Credit', 'Platinum Credit', 'Premium Debit']

device                    | Уникальных:       9 | Соотношение: 0.000001
                          Значения: ['Android App', 'Chip Reader', 'Chrome', 'Edge', 'Firefox', 'Magnetic Stripe', 'NFC Payment', 'Safari', 'iOS App']

channel                   | Уникальных:       3 | Соотношение: 0.000000
                          Значения: ['mobile', 'pos', 'web']

device_fingerprint        | Уникальных:  785462 | Соотношение: 0.104955

ip_address                | Уникальных: 7477187 | Соотношение: 0.999121

In [5]:
def optimize_dataframe_memory(df: pd.DataFrame) -> pd.DataFrame:
    """
    Оптимизируем типы данных для экономии памяти.
    
    Args:
        df: DataFrame для оптимизации
        
    Returns:
        pd.DataFrame: Оптимизированный DataFrame
    """
    df_optimized = df.copy()
    
    print("=== ОПТИМИЗАЦИЯ ТИПОВ ДАННЫХ ===")
    
    # 1. Оптимизация integer столбцов (Int64 -> Int32 если возможно)
    int_columns = ['card_number', 'num_transactions', 'unique_merchants', 'unique_countries']
    
    for col in int_columns:
        if col in df_optimized.columns:
            min_val = df_optimized[col].min()
            max_val = df_optimized[col].max()
            
            # Проверяем, помещается ли в int32 (-2,147,483,648 до 2,147,483,647)
            if min_val >= -2**31 and max_val <= 2**31 - 1:
                old_memory = df_optimized[col].memory_usage(deep=True) / 1024**2
                df_optimized[col] = df_optimized[col].astype('int32')
                new_memory = df_optimized[col].memory_usage(deep=True) / 1024**2
                print(f"{col:25} | int64 -> int32 | {old_memory:6.1f} MB -> {new_memory:6.1f} MB")
            else:
                print(f"{col:25} | Остается int64 (значения не помещаются в int32)")
    
    # 2. Оптимизация categorical столбцов
    categorical_candidates = {
        'customer_id': 'Уникальный идентификатор клиента - ограниченное множество',
        'vendor_category': 'Категория продавца - ограниченное множество',
        'vendor_type': 'Тип продавца - ограниченное множество', 
        'vendor': 'Название продавца - ограниченное множество',
        'country': 'Страна - ограниченное множество',
        'city': 'Город - ограниченное множество',
        'city_size': 'Размер города - ограниченное множество',
        'card_type': 'Тип карты - ограниченное множество',
        'device': 'Устройство - может быть много уникальных, но повторяющихся',
        'channel': 'Канал - ограниченное множество',
        'device_fingerprint': 'Уникальный отпечаток устройства - ограниченное множество',
    }
    
    print("\n=== КОНВЕРТАЦИЯ В CATEGORICAL ===")
    for col, description in categorical_candidates.items():
        if col in df_optimized.columns:
            unique_count = df_optimized[col].nunique()
            total_count = len(df_optimized)
            ratio = unique_count / total_count
            
            # Конвертируем в categorical если соотношение уникальных значений < 0.5
            if ratio < 0.5:
                old_memory = df_optimized[col].memory_usage(deep=True) / 1024**2
                df_optimized[col] = df_optimized[col].astype('category')
                new_memory = df_optimized[col].memory_usage(deep=True) / 1024**2
                print(f"{col:25} | string -> category | {old_memory:6.1f} MB -> {new_memory:6.1f} MB | Ratio: {ratio:.4f}")
            else:
                print(f"{col:25} | Остается string (слишком много уникальных: {ratio:.4f})")
    
    return df_optimized

# Применяем оптимизацию
df_transactions_optimized = optimize_dataframe_memory(df_transactions)
df_transactions_optimized

=== ОПТИМИЗАЦИЯ ТИПОВ ДАННЫХ ===
card_number               | Остается int64 (значения не помещаются в int32)
num_transactions          | int64 -> int32 |   57.1 MB ->   28.5 MB
unique_merchants          | int64 -> int32 |   57.1 MB ->   28.5 MB
unique_countries          | int64 -> int32 |   57.1 MB ->   28.5 MB

=== КОНВЕРТАЦИЯ В CATEGORICAL ===
customer_id               | string -> category |  421.1 MB ->   14.7 MB | Ratio: 0.0007
vendor_category           | string -> category |  406.8 MB ->    7.1 MB | Ratio: 0.0000
vendor_type               | string -> category |  399.1 MB ->    7.1 MB | Ratio: 0.0000
vendor                    | string -> category |  416.5 MB ->    7.1 MB | Ratio: 0.0000
country                   | string -> category |  393.0 MB ->    7.1 MB | Ratio: 0.0000
city                      | string -> category |  433.7 MB ->    7.1 MB | Ratio: 0.0000
city_size                 | string -> category |  392.3 MB ->    7.1 MB | Ratio: 0.0000
card_type                 | string -> category |  438.4 MB ->    7.1 MB | Ratio: 0.0000
device                    | string -> category |  401.7 MB ->    7.1 MB | Ratio: 0.0000
channel                   | string -> category |  377.6 MB ->    7.1 MB | Ratio: 0.0000
device_fingerprint        | string -> category |  578.1 MB ->  105.3 MB | Ratio: 0.1050

,transaction_id,customer_id,card_number,timestamp,vendor_category,vendor_type,vendor,amount,country,city,city_size,card_type,is_card_present,device,channel,device_fingerprint,ip_address,is_outside_home_country,is_high_risk_vendor,is_weekend,is_fraud,num_transactions,total_amount,unique_merchants,unique_countries,max_single_amount
0,TX_a0ad2a2a,CUST_72886,6646734767813109,2024-09-30 00:00:01.034820,Restaurant,fast_food,Taco Bell,394.658011,UK,Unknown City,medium,Platinum Credit,False,iOS App,mobile,e8e6160445c935fd0001501e4cbac8bc,197.153.60.199,False,False,False,False,1197,4.483492e+07,105,12,2.577089e+06
1,TX_3599c101,CUST_70474,376800864692727,2024-09-30 00:00:01.764464,Entertainment,gaming,Steam,619.905757,Brazil,Unknown City,medium,Platinum Credit,False,Edge,web,a73043a57091e775af37f252b3a32af9,208.123.221.203,True,True,False,True,509,3.701207e+06,100,12,9.474609e+05
2,TX_a9461c6d,CUST_10715,5251909460951913,2024-09-30 00:00:02.273762,Grocery,physical,Whole Foods,719.506409,Japan,Unknown City,medium,Platinum Credit,False,Firefox,web,218864e94ceaa41577d216b149722261,10.194.159.204,False,False,False,False,332,2.746928e+05,97,12,1.299151e+04
3,TX_7be21fc4,CUST_16193,376079286931183,2024-09-30 00:00:02.297466,Gas,major,Exxon,436.808287,Australia,Unknown City,medium,Premium Debit,False,iOS App,mobile,70423fa3a1e74d01203cf93b51b9631d,17.230.177.225,False,False,False,False,764,1.524784e+07,105,12,1.424024e+06
4,TX_150f490b,CUST_87572,6172948052178810,2024-09-30 00:00:02.544063,Healthcare,medical,Medical Center,434.430069,Nigeria,Unknown City,medium,Basic Debit,False,Chrome,web,9880776c7b6038f2af86bd4e18a1b1a4,136.241.219.151,True,False,False,True,218,2.892989e+03,88,12,6.934776e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7483761,TX_58a762fa,CUST_11344,377055034743699,2024-10-30 23:59:58.926575,Retail,online,AliExpress,670.362079,Singapore,Unknown City,medium,Premium Debit,False,Safari,web,2e37bb086e754bfaf2ec3806dcac8d98,248.8.111.152,False,False,False,False,1,1.149682e+03,1,1,6.703641e+02
7483762,TX_dabcf671,CUST_38961,373625915641065,2024-10-30 23:59:58.950801,Grocery,physical,Kroger,385.402905,France,Unknown City,medium,Platinum Credit,False,Chrome,web,459c67dbfbb15019df8088fc0f2ffe1d,224.123.137.90,False,False,False,False,0,3.854078e+02,0,0,3.854078e+02
7483763,TX_ab567eb4,CUST_75576,6702342842796660,2024-10-30 23:59:58.972155,Grocery,physical,Kroger,296.122166,Singapore,Unknown City,medium,Premium Debit,False,Safari,web,337d36a8f5e811564a1dd3c255db01dd,31.196.9.234,False,False,False,False,0,2.961227e+02,0,0,2.961227e+02
7483764,TX_5ae61846,CUST_82508,374615717295581,2024-10-30 23:59:58.996608,Retail,online,eBay,601.710000,USA,Chicago,large,Basic Credit,False,Firefox,web,52874c17f4ab0846fac1aed0c66e8551,188.74.107.8,False,False,False,False,2,1.474510e+03,2,1,6.017100e+02
7483765,TX_54fccca9,CUST_20139,373017396639208,2024-10-30 23:59:59.101885,Grocery,online,Walmart Grocery,265.526634,Japan,Unknown City,medium,Gold Credit,False,Chrome,web,e9e0e0db1c95f5f44613492b2f931fac,205.233.99.48,False,False,False,False,0,2.655266e+02,0,0,2.655266e+02

In [6]:
# Сравнение результатов оптимизации
print("=== СРАВНЕНИЕ ДО И ПОСЛЕ ОПТИМИЗАЦИИ ===")

# Общее потребление памяти
original_memory = df_transactions.memory_usage(deep=True).sum() / 1024**3
optimized_memory = df_transactions_optimized.memory_usage(deep=True).sum() / 1024**3
savings = original_memory - optimized_memory
savings_percent = (savings / original_memory) * 100

print(f"Исходный размер:      {original_memory:.3f} GB")
print(f"Оптимизированный:     {optimized_memory:.3f} GB")
print(f"Экономия:             {savings:.3f} GB ({savings_percent:.1f}%)")

print("\n=== ДЕТАЛЬНОЕ СРАВНЕНИЕ ТИПОВ ===")
print(f"{'Столбец':25} | {'Было':15} | {'Стало':15} | {'Экономия MB':12}")
print("-" * 80)

for col in df_transactions.columns:
    original_mem = df_transactions[col].memory_usage(deep=True) / 1024**2
    optimized_mem = df_transactions_optimized[col].memory_usage(deep=True) / 1024**2
    savings_col = original_mem - optimized_mem
    
    original_dtype = str(df_transactions[col].dtype)
    optimized_dtype = str(df_transactions_optimized[col].dtype)
    
    if savings_col > 0.1:  # Показываем только значимые изменения
        print(f"{col:25} | {original_dtype:15} | {optimized_dtype:15} | {savings_col:8.1f}")

print(f"\n=== ИНФОРМАЦИЯ ОБ ОПТИМИЗИРОВАННОМ ДАТАФРЕЙМЕ ===")
print(df_transactions_optimized.info(memory_usage='deep'))

=== СРАВНЕНИЕ ДО И ПОСЛЕ ОПТИМИЗАЦИИ ===
Исходный размер:      5.882 GB
Оптимизированный:     1.430 GB
Экономия:             4.453 GB (75.7%)

=== ДЕТАЛЬНОЕ СРАВНЕНИЕ ТИПОВ ===
Столбец                   | Было            | Стало           | Экономия MB
--------------------------------------------------------------------------------
customer_id               | object          | category        |    406.4
vendor_category           | object          | category        |    399.7
vendor_type               | object          | category        |    391.9
vendor                    | object          | category        |    409.4
country                   | object          | category        |    385.8
city                      | object          | category        |    426.6
city_size                 | object          | category        |    385.2
card_type                 | object          | category        |    431.2
device                    | object          | category        |    394.6
channel                   | object          | category        |    370.5
device_fingerprint        | object          | category        |    472.8
num_transactions          | int64           | int32           |     28.5
unique_merchants          | int64           | int32           |     28.5
unique_countries          | int64           | int32           |     28.5

=== ИНФОРМАЦИЯ ОБ ОПТИМИЗИРОВАННОМ ДАТАФРЕЙМЕ ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7483766 entries, 0 to 7483765
Data columns (total 26 columns):
 #   Column                   Dtype
---  ------                   -----
 0   transaction_id           object
 1   customer_id              category
 2   card_number              int64
 3   timestamp                datetime64[us]
 4   vendor_category          category
 5   vendor_type              category
 6   vendor                   category
 7   amount                   float64
 8   country                  category
 9   city                     category
 10  city_size                category
 11  card_type                category
 12  is_card_present          bool
 13  device                   category
 14  channel                  category
 15  device_fingerprint       category
 16  ip_address               object
 17  is_outside_home_country  bool
 18  is_high_risk_vendor      bool
 19  is_weekend               bool
 20  is_fraud                 bool
 21  num_transactions         int32
 22  total_amount             float64
 23  unique_merchants         int32
 24  unique_countries         int32
 25  max_single_amount        float64
dtypes: bool(5), category(11), datetime64[us](1), float64(3), int32(3), int64(1), object(2)
memory usage: 1.4 GB
None

In [7]:
# Дополнительная проверка: убеждаемся что данные не изменились
print("=== ПРОВЕРКА ЦЕЛОСТНОСТИ ДАННЫХ ===")

# Проверяем, что количество строк осталось прежним
print(f"Исходное количество строк: {len(df_transactions)}")
print(f"После оптимизации: {len(df_transactions_optimized)}")

# Проверяем несколько ключевых столбцов на равенство значений
test_columns = ['transaction_id', 'amount', 'is_fraud', 'ip_address', 'card_number']
for col in test_columns:
    if col in df_transactions.columns:
        are_equal = df_transactions[col].equals(df_transactions_optimized[col])
        print(f"Столбец {col}: {'✓ идентичен' if are_equal else '✗ РАЗЛИЧАЕТСЯ'}")

print("\n=== УНИКАЛЬНЫЕ ЗНАЧЕНИЯ В CATEGORICAL СТОЛБЦАХ ===")
categorical_cols = df_transactions_optimized.select_dtypes(include=['category']).columns
for col in categorical_cols:
    unique_count = df_transactions_optimized[col].nunique()
    categories = sorted(df_transactions_optimized[col].cat.categories.tolist())
    print(f"{col:20} | {unique_count:3} категорий: {categories[:20]}")

# Сохраняем оптимизированный датафрейм
print("\n=== СОХРАНЕНИЕ ОПТИМИЗИРОВАННЫХ ДАННЫХ ===")
output_file = 'transactions_usd_optimized.parquet'
df_transactions_optimized.to_parquet(output_file, compression='snappy')

# Проверяем размер файлов
import os
original_size = os.path.getsize('transactions_usd.parquet') / 1024**2
optimized_size = os.path.getsize(output_file) / 1024**2
file_savings = original_size - optimized_size
file_savings_percent = (file_savings / original_size) * 100

print(f"Размер исходного файла:      {original_size:.1f} MB")
print(f"Размер оптимизированного:    {optimized_size:.1f} MB") 
print(f"Экономия места на диске:     {file_savings:.1f} MB ({file_savings_percent:.1f}%)")
print(f"Файл сохранен как: {output_file}")

=== ПРОВЕРКА ЦЕЛОСТНОСТИ ДАННЫХ ===
Исходное количество строк: 7483766
После оптимизации: 7483766
Столбец transaction_id: ✓ идентичен
Столбец amount: ✓ идентичен
Столбец is_fraud: ✓ идентичен
Столбец ip_address: ✓ идентичен
Столбец card_number: ✓ идентичен

=== УНИКАЛЬНЫЕ ЗНАЧЕНИЯ В CATEGORICAL СТОЛБЦАХ ===
customer_id          | 4869 категорий: ['CUST_10000', 'CUST_10018', 'CUST_10022', 'CUST_10039', 'CUST_10102', 'CUST_10109', 'CUST_10129', 'CUST_10150', 'CUST_10161', 'CUST_10198', 'CUST_10207', 'CUST_10213', 'CUST_10332', 'CUST_10335', 'CUST_10365', 'CUST_10386', 'CUST_10407', 'CUST_10417', 'CUST_10454', 'CUST_10466']
vendor_category      |   8 категорий: ['Education', 'Entertainment', 'Gas', 'Grocery', 'Healthcare', 'Restaurant', 'Retail', 'Travel']
vendor_type          |  17 категорий: ['airlines', 'booking', 'casual', 'events', 'fast_food', 'gaming', 'hotels', 'local', 'major', 'medical', 'online', 'pharmacy', 'physical', 'premium', 'streaming', 'supplies', 'transport']
vendor               | 105 категорий: ['AMC Theaters', 'Airbnb', 'Aldi', 'AliExpress', 'Amazon', 'Amazon Fresh', 'Amazon Prime', 'American Airlines', 'Apple Music', "Applebee's", 'BP', 'Barnes & Noble', 'Best Buy', 'Booking.com', 'Burger King', 'CVS Pharmacy', 'Capital Grille', 'Careem', 'Chegg', 'Chevron']
country              |  12 категорий: ['Australia', 'Brazil', 'Canada', 'France', 'Germany', 'Japan', 'Mexico', 'Nigeria', 'Russia', 'Singapore', 'UK', 'USA']
city                 |  11 категорий: ['Chicago', 'Dallas', 'Houston', 'Los Angeles', 'New York', 'Philadelphia', 'Phoenix', 'San Antonio', 'San Diego', 'San Jose', 'Unknown City']
city_size            |   2 категорий: ['large', 'medium']
card_type            |   5 категорий: ['Basic Credit', 'Basic Debit', 'Gold Credit', 'Platinum Credit', 'Premium Debit']
device               |   9 категорий: ['Android App', 'Chip Reader', 'Chrome', 'Edge', 'Firefox', 'Magnetic Stripe', 'NFC Payment', 'Safari', 'iOS App']
channel              |   3 категорий: ['mobile', 'pos', 'web']
device_fingerprint   | 785462 категорий: ['0000104cd168386a335ba6bf6e32219d', '0000193a728fd00b6cff91b8840bbf8d', '000053b1e684c9e7ea73727b2238ce18', '00005d011db80a956aab176cc94d1d37', '00007c55a9a7591b98a76d79216c9112', '000093856b4e947511870f3e10464129', '0000a0f5746d603088ac968c91b085b5', '0000b2815cc3c2b56867cbbf4d36efa5', '0000e19d6a5608e3787e5bfea98488ca', '0000e9af7421452e8001a374085ca53b', '000109e6bf54b3b20e8547b6026bc355', '0001181bf1ad8f82dcf59c7c18343bd5', '0001261e2060303a06ba6c64d676d639', '000133296ef6b63b0210f224e1347365', '000163671e7b29522ad47604f3b48cca', '00017961865c4f766fdbb3cd8fe0bfb0', '000194844eb756f41ab6a0cc47340fd5', '00019d812c1173c8a69c656a40fa8767', '0001a104d98f901d4ea337c1d67ec3e3', '0001acb84c32594ead72336aa60ae0f0']

=== СОХРАНЕНИЕ ОПТИМИЗИРОВАННЫХ ДАННЫХ ===
Размер исходного файла:      631.2 MB
Размер оптимизированного:    623.5 MB
Экономия места на диске:     7.7 MB (1.2%)
Файл сохранен как: transactions_usd_optimized.parquet

## Итоговая сводка по оптимизации типов данных

### Применённые оптимизации:

1. **Integer оптимизация (Int64 → Int32)**
   - Экономия: ~50% памяти для этих столбцов (если значения помещаются в int32)

2. **String → Categorical конвертация**
   - Экономия: ~90% памяти для этих столбцов


### Критерии принятия решений:

- **Int32 vs Int64:** Проверяем диапазон значений (-2¹³¹ до 2³¹-1)
- **Categorical vs String:** Соотношение уникальных значений < 0.5 от общего количества
- **Безопасность:** Сохраняем все исходные данные без потерь

### Результаты:
- Экономия памяти: 75% 
- Ускорение операций группировки и фильтрации для categorical столбцов

# Переходим к EDA с оптимизированными данными

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

### Сравним скорость чтения файлов

In [5]:
%%time
df_transactions_optimized = pd.read_parquet('transaction_fraud_data.parquet')

CPU times: total: 27.2 s
Wall time: 19 s

In [6]:
%%time
df_transactions_optimized = pd.read_parquet('transactions_usd.parquet')

CPU times: total: 17.3 s
Wall time: 11.3 s

In [7]:
%%time
df_transactions_optimized = pd.read_parquet('transactions_usd_optimized.parquet')

CPU times: total: 10.7 s
Wall time: 7.1 s

### Вывод: после всех оптимизаций ускорение чтения файла: с 19 секунд до 7 секунд (почти в 3 раза, но учитываем что я читаю их последовательно, так что оптимизированный файл в реальности читается даже быстрее)